name: .NET Core Desktop Build and Release

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'  # 触发版本标签时发布
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Debug Repository Structure
      run: |
        Write-Host "GitHub Workspace: $env:GITHUB_WORKSPACE"
        Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse | Select-Object FullName
        Get-ChildItem
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    
    - name: Restore the application
      run: |
        $solutionFile = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Filter "*.sln" | Select-Object -First 1
        
        if ($solutionFile) {
          Write-Host "Found solution file: $($solutionFile.FullName)"
          msbuild "$($solutionFile.FullName)" /t:Restore /p:Configuration=${{ matrix.configuration }}
        } else {
          Write-Error "No solution file found in the repository"
          exit 1
        }
    
    - name: Build Solution
      run: |
        $solutionFile = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Filter "*.sln" | Select-Object -First 1
        
        if ($solutionFile) {
          msbuild "$($solutionFile.FullName)" /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU"
        } else {
          Write-Error "No solution file found in the repository"
          exit 1
        }
    
    - name: Create Artifact Package
      run: |
        # 假设输出在 bin 目录下
        $outputPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "bin\${{ matrix.configuration }}"
        New-Item -ItemType Directory -Path "$env:GITHUB_WORKSPACE\publish" -Force
        Copy-Item -Path "$outputPath\*" -Destination "$env:GITHUB_WORKSPACE\publish" -Recurse
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: desktop-app-${{ matrix.configuration }}
        path: ${{ github.workspace }}\publish

    # 仅在推送标签时发布到 GitHub Release
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ github.workspace }}\publish\**\*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
