name: .NET Core Desktop
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # Debug steps to verify repository structure
    - name: Debug Repository Structure
      run: |
        # Print current workspace directory
        Write-Host "GitHub Workspace: $env:GITHUB_WORKSPACE"
        
        # List all files and directories in the workspace
        Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse | Select-Object FullName

        # Print the current directory contents
        Get-ChildItem

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    
    - name: Restore the application
      run: |
        # Find the solution file dynamically
        $solutionFile = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Filter "*.sln" | Select-Object -First 1
        
        if ($solutionFile) {
          Write-Host "Found solution file: $($solutionFile.FullName)"
          msbuild "$($solutionFile.FullName)" /t:Restore /p:Configuration=${{ matrix.configuration }}
        } else {
          Write-Error "No solution file found in the repository"
          exit 1
        }
